### ISSUE TITLE
sagews --> pdf conversion doesn't work for img inside anchor tag in html block

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#100]
Here's an example:

  https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2015-09-06-035035-print-issue.sagews

The only input cell is:

```
%html
<a href="http://tinypic.com?ref=16i5ngz" target="_blank">
    <img src="http://i57.tinypic.com/16i5ngz.png" border="0" alt="Image and video hosting by TinyPic">
</a>
```

**Comment by billpage** [comment]
Another conversion issue: Pretty printing a matrix

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/print-issue-3.sagews

https://cloud.sagemath.com/projects/b04b5777-e269-4c8f-a4b8-b21dbe1c93c6/files/print-issue-3.pdf
Only input cell is:

    %sage
    show(matrix([[1,2],[3,4]])

**Comment by haraldschilly** [comment]
the matrix issue is #232

**Comment by haraldschilly** [comment]
my recent work on sagews2pdf solved embedding an image via markdown (`![](...)`) and via an img tag. it supports all kinds of formats (it is optimistic) and converts src links to SVGs to PDF. what it doesn't solve is an image **inside** an anchor a link. The html parser is happily emitting converted tags, but the resulting latex is still wrong. Hence, exactly this issue here is still open, while some related ones are solved.

**Comment by williamstein** [comment]
I just made this issue far more precise so that it is do-able.

**Comment by haraldschilly** [comment]
ok, I've assigned myself. Maybe a fresh look solves this, but I have to take care to not rip open old wounds.
