### ISSUE TITLE
improve projects/new project UI

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1016]
The enhanced dialog for creating a new project in [projects.cjsx](https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/projects.cjsx) has a couple of issues.
- [ ] deduplicate the code from [project_settings](https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/project_settings.cjsx) since [this patch](https://github.com/sagemathinc/smc/commit/c29b274f91e8172ce062786c8c8d99dd4d11b33e#diff-1d4654a4776f0825cd0ac2f439629410) fixes a couple of issues that aren't there yet. The best strategy would be to use one single component that's used in both places!
- [ ] It is confusing to show so much information to new users. Instead, condense this to a clear explanation and only reveal the upgrade dialog with billing information, when a button is pressed.
- [ ] If a user is already a member, show the upgrade dialog directly. Additionally, in such a case when there are unused quotas for internet and member hosting left, automatically apply them for a newly created project (it's sensible to assume, that with unused upgrades a user wants to use them -- and explicitly unchecks the box if not)

**Comment by haraldschilly** [comment]
see also https://github.com/sagemathinc/smc/issues/1015

**Comment by timothyclemansinsea** [comment]
Code deduplication needs to be its an own issue because it's such an involved task. I tried to do it and failed. 

My proposal:
Change explanation text to "A project is your own private computational workspace that you can share with others. Each project is free. What's not free is members only hosting and direct use of internet resources. Project resources like ram, cpu, and disk space can be upgraded. If you have any questions, please email help@sagemath.com immediately."
Have three buttons:
"Create project without any upgrades"
"Create project with members only hosting and direct internet access"
"Create project with customized upgrades"

Subscription/billing only show up if the 2nd button is clicked and upgrade is not possible without changing subscription/upgrade allocation or the 3rd button is clicked.

**Comment by timothyclemansinsea** [comment]
If I end up doing this I would like to break this down into a few E-easy/E-medium issues rather than one big E-hard issue.

**Comment by timothyclemansinsea** [comment]
This either needs to be closed or updated given the recent improvements.
