### ISSUE TITLE
trying to open a file in the log that no longer exists results in a confusing and non-professional error message

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1078]
<img width="1415" alt="screen shot 2016-10-18 at 9 35 41 pm" src="https://cloud.githubusercontent.com/assets/1276278/19505835/ed61fb12-957a-11e6-9440-d2e77620e879.png">

**Comment by williamstein** [comment]
The message above is "You should not be here! editor-smc/src/smc-webapp/client_browser.coffee".

**Comment by johnjeng** [comment]
In this case do we want to create a new file or give a more professional/helpful error message?

**Comment by williamstein** [comment]
> In this case do we want to create a new file or give a more professional/helpful error message?

You could put a professional message, then have a button to create the file, and another to cancel/close.

**Comment by haraldschilly** [comment]
I've pushed 284c71f595c5d986ee245c to fix the strings, but the problem is definitely deeper. I.e. I have seen that string before, but I wasn't able to replicate it. If I'm reading the code correctly, maybe the actual problem is that `open_files` is sometimes not defined? So maybe, this is actually some race condition?

Also, more general, I think files opened from the log shouldn't be created. There should be exactly this message that this file no longer exists there. (I'm always rolling with my eyes, if I accidentally create an empty file by clicking in the log)

**Comment by williamstein** [comment]
The problem is gone, but now it creates the file.  @haraldschilly maybe you want to create a new issue to handle that, though I don't consider this a flat out bug anymore (it was the behavior before).  Anyways, now there is no "nonprofessional error message".
