### ISSUE TITLE
Side chat needs explanation similar to that of chat editor saying to hit shift-enter 

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#1241]

**Comment by williamstein** [comment]
fixed in sidechatright (it's a 1-liner).  This should really be in the todo list for sidechatright.

**Comment by williamstein** [comment]
(that said, I totally agree with this ticket.)

**Comment by williamstein** [comment]
<img width="552" alt="screen shot 2016-11-16 at 5 55 17 am" src="https://cloud.githubusercontent.com/assets/1276278/20349895/482cdb96-abc1-11e6-8d5d-f757dbb53fe8.png">

**Comment by timothyclemansinsea** [comment]
Hmmm I would put shift-enter before markdown info just because it's the #1
thing one needs to know

**Comment by williamstein** [comment]
(1) Before you even type in the box it says Shift enter right there.
(2) There is a big blue send button.  You do not ever **need** to know about shift+enter. 
(3) Once you know about shift+enter, you never need to be told about it again....
(4) People are likely to expect shift+enter already in SMC, since it's how you submit code in sagews and jupyter, and our users are mainly using sagews and jupyter.

**Comment by timothyclemansinsea** [comment]
Because no other chat system I use uses shift-enter as send I'm constantly
forgetting.

**Comment by timothyclemansinsea** [comment]
For some reason I totally missed "Type a message, then shift-enter" Maybe
make shift-enter bold?

**Comment by williamstein** [comment]
Well despite all I wrote, I'm changing it so shift+enter is first, as you recommended.
