### ISSUE TITLE
support Jupyter notebooks with Firefox (was: issues with timetravel; exceptions)

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#1262]
in **firefox 50.0**, the following causes an exception:

1. create ipynb file, add a few cells
2. time travel
3. go back a revision and well, then I get an exception.

```
Notebook failed to load from JSON: (this is in jupyter's main.js.min!)
TypeError: fontSize is undefined
Stack trace:
OutputArea.prototype._should_scroll
OutputArea.prototype.scroll_if_long
OutputArea.prototype.expand
OutputArea.prototype.append_output
OutputArea.prototype.fromJSON
```

but I'm not sure, if this is definitely caused by time travel or just a side effect. there were also other exceptions, but not sure what to do about them.

**Comment by haraldschilly** [comment]
playing with this a bit more, that stacktrace might be caused by timetravel itself and once it happens, it causes it to be dysfunctional.

**Comment by williamstein** [comment]
I looked into this for over an hour.  Basically any time using the Jupyter fromJSON command (in any context with any input), it throws an exception.  This is a bug in Jupyter or Firefox 50.  The relevant code in jupyter references using some trick from stackoverflow, in a sloppy way (it's basically the standard undefined mistake, which is much easier to make in straight javascript than coffeescript).  

The sad upshot: **Jupyter in SMC is totally massively broken in Firefox 50 now**.  I don't know about previous versions of Firefox -- however, we've had reports of corruption periodically, and maybe they were all in Firefox.  Just using Jupyter sync with multiple browsers is likely to cause huge trouble.     In 

 https://github.com/sagemathinc/smc/commit/4895a642e2f17370a0594159dc2b61b4561c672c

I've just completely banned use of Jupyter in Firefox until we properly fix this, which will likely involve having a custom patch to Jupyter.   Otherwise, every user is going to end up with corruption issues constantly. 

<img width="627" alt="screen shot 2016-11-20 at 10 24 03 pm" src="https://cloud.githubusercontent.com/assets/1276278/20472629/13a0765a-af70-11e6-80e2-ae0aaaeadcdb.png">

**Comment by williamstein** [comment]
Changing from bug to enhancement -- since there is now a clear message and nothing is clearly broken for a user.

**Comment by jasongrout** [comment]
@williamstein, @haraldschilly - Notebook 4.3.1 (now released) has a fix - https://github.com/jupyter/notebook/issues/1956
