### ISSUE TITLE
some sws (old sagenb) files that won't convert to sagews properly (one gets an error)

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1587]
See attached:

[resageincalculus.zip](https://github.com/sagemathinc/smc/files/728097/resageincalculus.zip)

To work on this:

1. Open zip file and try to open sws files in SMC (or use smc-sws2sagews).
2. Observe and fix errors.  Some easy python traceback or something...

**Comment by DrXyzzy** [comment]
See also attached:

[f09.zip](https://github.com/sagemathinc/smc/files/1006831/f09.zip)

with 3 .sws files from https://www.calvin.edu/~rpruim/courses/m232/F09/sage/.

At this point, I have patched `smc-sws2sagews` so that 5 of the 6 .sws files in the two zip archives which date from 2009 are converted to usable .sagews files.

I'm now working on the last file, `fclali34.sws`, which is from 2011, but does not convert correctly.

**Comment by williamstein** [comment]
Yeah!
