### ISSUE TITLE
Install graph-tool on smc

### ISSUE THREAD

**Issue by lahvak** [sagemathinc/smc#1651]
Graph-tool  (http://graph-tool.skewed.de/) is a mixed python and c++ module for graph analysis.  Although it is a python module, its internals are written in c++, and depend on number of c++ libraries, which apparently makes it impossible to be installed with pip.

There are Debian and Ubuntu packages provided, or it can be compiled from source.  Instructions for installation or compilation are at https://git.skewed.de/count0/graph-tool/wikis/installation-instructions

**Comment by haraldschilly** [comment]
Hello @lahvak ... this is unfortunately not so easy. However, I've installed the deb packages and at least they are doing something. See this terminal session:

```
⋊> ~/build on master ⨯ ipython3
[...] 
In [1]: import graph_tool
 
In [2]: graph_tool
Out[2]: <module 'graph_tool' from '/usr/lib/python3/dist-packages/graph_tool/__init__.py'>
 
In [3]: g = graph_tool.Graph()
 
In [4]: g
Out[4]: <Graph object, directed, with 0 vertices and 0 edges at 0x7fce1d68aa90>
```
I've also installed it in anaconda, our main python 3 environment, but it fails for various reasons. I think the one [providing that channel](https://anaconda.org/ostrokach/graph-tool) hasn't updated the build recently.  So that's  a bit unfortunate.
