### ISSUE TITLE
bug in markdown rendering of inline latex -- too aggressive backslash escaping

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#1801]
Put this in a sage worksheet (or any Markdown-rendered content in SMC):
```
%md
Displayed matrix works:
$$ \begin{bmatrix}
    a & b \\ b & c
\end{bmatrix}$$

Non-displayed matrix does not work due to some backslash escaping we do not want touching tex:
$\begin{bmatrix}
    a & b \\ b & c
\end{bmatrix}$

Proof that this is the problem:
$\begin{bmatrix}
    a & b \\\\ b & c
\end{bmatrix}$
```

It comes out wrong:

<img width="1002" alt="screen shot 2017-03-23 at 1 11 07 pm" src="https://cloud.githubusercontent.com/assets/1276278/24268228/3a3b7ae8-0fca-11e7-9c18-acc1844913f7.png">

%html works fine though:

<img width="778" alt="screen shot 2017-03-23 at 1 11 41 pm" src="https://cloud.githubusercontent.com/assets/1276278/24268233/4663a89a-0fca-11e7-976e-ccd0407c38e7.png">

Example worksheet: https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2017-03-23-130654-matrix-md.sagews

**Comment by haraldschilly** [comment]
I've worked on this for at least an hour and I have no idea how to fix this. I'm rather arguing that this is supposed to not work, because `$` is either for single-line formulas or for dollar amounts. All variations or tweaks I tried did either lead to problems or didn't catch this. The piece in the puzzle that escapes backslashes is `marked`. I.e. 

*  `marked("foo \\ bar")` → `"<p>foo \ bar</p>"`
* `marked("foo \\\\ bar")` → `"<p>foo \ bar</p>"` (still just one, weird)
* `marked("foo \\ \\ bar")` → `"<p>foo \ \ bar</p>`

Another detail to note is, that `bmatrix` is a valid mathjax environment -- see [mathjax environments](http://docs.mathjax.org/en/latest/tex.html#environments). I suggest to support all of them (see followup #1822 ), and with commit 020486ed2984a496aa2dd81c5c44c8476ec299af the following `$`-free markdown text works:

```
\begin{bmatrix}
    r & s \\ s & t
\end{bmatrix}
```

what's working in any case is

```
$\begin{bmatrix}i & j \\ j & k\end{bmatrix}$
```

If someone wants to pick this up, here is my full test document using different letters such that the cases can be distinguished:

```
A

$$\begin{bmatrix}
    a & b \\ b & c
\end{bmatrix}$$

B

$\begin{bmatrix}
    x & y \\ y & z
\end{bmatrix}$

C

$\begin{bmatrix}
    u & v \\\\ v & w
\end{bmatrix}$

D

\begin{bmatrix}
    r & s \\ s & t
\end{bmatrix}

E

$\begin{bmatrix}i & j \\ j & k\end{bmatrix}$
```

time: 70 minutes

**Comment by williamstein** [comment]
Jupyter Notebook works fine with the test input.  I wonder how they do it?

<img width="937" alt="screen shot 2017-05-17 at 10 38 32 pm" src="https://cloud.githubusercontent.com/assets/1276278/26188031/9f685780-3b51-11e7-8f21-42651e2094e5.png">

Here's the relevant Jupyter notebook file: https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/textcell.js

**Comment by williamstein** [comment]
We definitely need to properly fix this.   Regarding

>  I'm rather arguing that this is supposed to not work, because $ is either for single-line formulas or for dollar amounts. 

that isn't a valid argument, since though you wish $ was only for single line formulas, it simply isn't.  In latex (and mathjax html) it definitely is fine to use $ for multiline formulas.

The Jupyter project **does** have what seems to be a proper complete solution to this problem, which is used in MarkdownCell.prototype.render of https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/textcell.js

They use https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/mathjaxutils.js to remove all math before feeding it to marked.  In smc-webapp/markdown.coffee, we use misc.parse_mathjax, which I wrote, and you improved... but which is still pretty simple and naive, at least compared to mathjaxutils.js.  

We should just include mathjaxutils.js in cocalc and use it instead of misc.parse_mathjax.  It's way more sophisticated, and mostly taken directly from mathjax itself.

**Comment by williamstein** [comment]
time: 34 minutes
