### ISSUE TITLE
Ctrl-M to go to command mode. 

### ISSUE THREAD

**Issue by Carreau** [sagemathinc/smc#1926]
Escape and Control-M (Ctrl even on Mac) goes to command mode. 

That's a legacy shortcut, it seem useful for new mac that have the new touchbar as well.

**Comment by williamstein** [comment]
time: 5 minutes

**Comment by williamstein** [comment]
process: uncomment `console.log 'shortcut', shortcut, cmd` in jupyter/keyboard.coffee, hit keys, add to commands.coffee

**Comment by Carreau** [comment]
Sweet, thanks. Still pulling the Docker images, I don't have a dev-install
working locally so couldn't make a PR :-)

**Comment by williamstein** [comment]
> Still pulling the Docker images, I don't have a dev-install working locally so couldn't make a PR :-)

Cool -- let me know how the Docker image goes, as you'll be the first (besides me) to try it, and I stayed up for hours last night getting it to work...

IMPORTANT: if you're going to dev of smc-in-smc following smc/src/dev/project/README.md on docker **on a mac**, you really need your project's directory to be in the VM image, not a mount from OS X, since Docker's external os x mounting is slow and not POSIX enough.   So just don't use the -v option when starting the image.  Of course, be sure to not just delete your image or you could lose data.

Don't hesitate with questions.

Also if you want to do any dev directly in SMC, I'm happy to completely setup a project for you that is ready to go...
