### ISSUE TITLE
sagews: return doesn't work after ")"

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#199]
In a sagews file in the editor, type in a ")" bracket and the cursor on the right hand side of it (default position after typing it in).

pressing the return key does not insert a new line.

**Comment by williamstein** [comment]
I just did some option bisecting, and this is caused by this codemirror plugin:

   Match brackets: highlight matching brackets near cursor

If you uncheck it in account settings and re-open your worksheet, the problem goes away.  

The same plugin doesn't cause trouble with a pure python file though.

It also doesn't cause trouble if there are no output widgets in the worksheet.  

To fix this we'll have to probably read and/or put debugging code in  http://codemirror.net/addon/edit/matchbrackets.js

**Comment by williamstein** [comment]
Even easier to replicate.  Make an empty worksheet that contains only:
`()`

**Comment by williamstein** [comment]
Still broken!

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-115723-issue199.sagews

**Comment by williamstein** [comment]
Hard due to having to really dive into codemirror mode internals...

**Comment by williamstein** [comment]
@haraldschilly  -- bet you're glad this is finally fixed!

**Comment by haraldschilly** [comment]
Hmm, cool! So it was some special-case handling for editors? I hope that doesn't break something else ...

**Comment by williamstein** [comment]
> So it was some special-case handling for editors

It did one thing -- allow for running some special optimized render/update code in a sagews on enter.   I think that was no longer needed though, due to my rewrite of rendering in April.
