### ISSUE TITLE
Add a default local path for R libraries for Jupyter

### ISSUE THREAD

**Issue by discnerd** [sagemathinc/smc#205]
Currently my solution is to just run .libPaths("~/R/x86_64-pc-linux-gnu-library/3.2") at the beginning of each Jupyter notebook.  However, I can't find how to change the default path so I don't have to do that. 

Also would it make sense to pull your list of preinstalled R packages from https://www.continuum.io/blog/developer/jupyter-and-conda-r?

**Comment by evelynmitchell** [comment]
I wanted to suggest you create a config file for jupyter called jupyter_notebook_config.py and put that in the project directory following:
http://jdfreder-notebook.readthedocs.org/en/latest/config.html

but jupyter notebooks on smc don't support R in the way that sage worksheets do.
My minimum example (sagews):

%r
sessionInfo()
.libPaths()
getwd()

Does not work in a jupyter notebook, because %r is not supported.

**Comment by williamstein** [comment]
This is too vague.
