### ISSUE TITLE
Print button inserts extra amp's in matrices

### ISSUE THREAD

**Issue by RobertLipshitz** [sagemathinc/smc#232]
In an SMC Sage Worksheet:

%typeset_mode True
matrix([[1,2,3],[4,5,6]])

Then click the "print" icon.  The result has extra "amp;"s (see attached).
![mxprinterror](https://github-cloud.s3.amazonaws.com/assets%2F7082437%2F10957192%2Fd518e182-8316-11e5-85ef-6f0f7192931a.png)

**Comment by Ahuchala** [comment]
I converted a sagews to a tex file, and then corrected everything I could find with the exception of:
- Lines trailing off the side of the document (often happens when given a single line with no spaces)
- Graphs that rendered in sagews didn't appear in the latex pdf
- Long lines often get an unwanted \ character at the end

I've attached links the original (bad) tex file generated in the sagews2pdf process, as well as a corrected version of it. Checking difs will allow one to see problems in the original that I changed.

Original (bad):
https://cloud.sagemath.com/projects/d0bf849e-0437-4f4f-9d61-c23a0d3474ae/files/fix-tex/original.tex

Fixed:
https://cloud.sagemath.com/projects/d0bf849e-0437-4f4f-9d61-c23a0d3474ae/files/fix-tex/fixed.tex

**Comment by haraldschilly** [comment]
plotting a latex-matrix has  been solved by my recent work on sagews2pdf. once my changes are reviewed and merged, this ticket can be closed. the solution here is to add an explicit conversion step of "html symbols" resulting from the md2html conversion, to latex, before the html parser is getting activated.

**Comment by williamstein** [comment]
live
