### ISSUE TITLE
port Andrey N.'s R interface plotting improvements to SageMathCloud

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#234]
See https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2015-11-05-170512-r-plots.sagews

**Comment by novoselt** [comment]
https://github.com/sagemath/sagecell/commit/1b0ba6fd8e823dd05466f1f0d91f15609e5638b5
- `r = R()` is don in the code run after forking a new kernel from "the master one"
- `local/lib/R/etc/Rprofile.site` is in `$SAGE_ROOT` and has to have a new line in the end
- `bitmapType='cairo'` should not be necessary, R is supposed to pickup cairo if available over X11, but for some reason it does not do it (I have no plans to investigate why)

https://github.com/sagemath/sagecell/commit/12466eb52d98eb203afbf89e61a6e0a1958bc5ce
- `device='svg'` makes default plotting done via SVG (otherwise it is either X11 or PDF depending on interactivity etc, neither is good for us)
- JS change actually adds Python code in the end of `print r.eval(...)` that look for default-named plot files and shows those that can be handled by browers, all other files in current directory get links to automatically

https://github.com/sagemath/sagecell/commit/7cfc9afd1619e2d332d955575e3dd80786cafaa8
this was cosmetic for no empty lines, don't know if cloud needs it

It was necessary to modify R interface in Sage as well:
https://github.com/novoselt/sage/commit/7e7f041e7a74dfe13c6daaed22b2534163494384
to allow picking up configuration files and
https://github.com/novoselt/sage/commit/410ffbc1c73cf8bf3f5305eb7e3e17d8b8dbf7ea
to allow picking up svg default from the configuration file.

**Comment by williamstein** [comment]
Another option: let's just switch to the official R Jupyter kernel, as suggested here:

https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-104428-issue234.sagews

and if there are issues/problems, we make **that** kernel better.  For example, that kernel is png  by default, which is really ugly.  Would need to fix that.  We would also want to test/update these worksheets:

https://github.com/sagemath/cloud-examples/tree/5db6a2be9dbae7edd100cd3fcba31128faeea90d/r

**Comment by williamstein** [comment]
we switched to the R jupyter kernel:  https://github.com/sagemathinc/smc/pull/1082
