### ISSUE TITLE
Provide support for peer-marking

### ISSUE THREAD

**Issue by mikecroucher** [sagemathinc/smc#306]
In some courses, it's desirable to allow students to mark each other's work. Could SMC implement something like this? The type of scheme I have in mind is:-

- Have a 'Distribute for peer marking' button in the assignment page that randomly assigns each student with an anonymous assignment to mark.

- Marking student marks the notebook and clicks 'Return to Student'.

**Comment by williamstein** [comment]
I very much want this as well.  When I used SMC in early 2014 (very early days) for teaching a course, I did pretty sophisticated peer grading using it!  I had about 40 students, and had each assignment get graded by 3 other people (can't remember), etc.   It was all coordinated via some complicated Python scripts, and extra functionality I had access to as admin of the site.   I very much want to make something like this live for everybody, since it's very interesting and useful.

**Comment by williamstein** [comment]
done!
