### ISSUE TITLE
make it possible to save 3d plots in sage worksheets

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#308]
This is a very tricky problem.   The goal would be to save to a file exactly what is displayed in the browser.  This currently sort of down to support printing a worksheet with 3d graphics in it.   

It's unclear what the api for this should be... or how it might work, since only the frontend browser can do the rendering.

**Comment by Eulerianial** [comment]
Do you think the Blender community might have some API for it? Since Blender too is written in Python, the data interoperability won't be an issue also. What I know is that Blender graphics can be saved/exported easily the way it comes in browser. So much so it can be even sent to a 3D printer. 

Let me find more on this and will update on this thread.

**Comment by williamstein** [comment]
I'm going to close this due to no further comments.  Also, you can now click "print" and at least save the generated latex, which will create png's of all 3d graphics, so that technically solves this problem.  Finally, the core problem should be solved in sage itself, not SMC -- you can already export 3d graphics using jmol, to obj format (for 3d printing), etc., and if you want blender (if it isn't there already) such functionality belongs as port of the .save method on 3d scenes.
