### ISSUE TITLE
Writing to stderr in .sagews does not render any output

### ISSUE THREAD

**Issue by MurrayT** [sagemathinc/smc#318]
None of 
```python
import sys

print >> sys.stderr, "Hello"

sys.stderr.write("Hello")

from __future__ import print_function

print("Hello", file=sys.stderr)
```
produce any output when run inside a .sagews document. They should all print to a visible `stderr` feed similar to tracebacks. The `from __future__ import print_function` version gives a syntax error as well.

**Comment by williamstein** [comment]
This works fine for me in a Sage Worksheet (and it should, knowing how they work):
```
import sys
print >> sys.stderr, "Hello"
sys.stderr.write("Hello")
```

See https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2015-12-06-172014-stderr.sagews

Regarding "The from __future__ import print_function version gives a syntax error as well.", that's because you can only use `from __future__ import print_function` at the top of a Python file -- it doesn't make sense to use it inside a block of code that is being eval'd during a session.

**Comment by MurrayT** [comment]
Does that mean that no `from x import y` statements will work? That may be the issue I was having.

**Comment by williamstein** [comment]
> Does that mean that no from x import y statements will work?

They will work fine in most cases.   `from __future__ import ...` in python is special.

Regarding `from sys import stderr`, this also works fine for me in Sage worksheets, and I don't see why it wouldn't... [example](https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2015-12-07-083157-stderr2.sagews).

Regarding your example, which is critical for me to understand the problem (1) you need to share it publicly for anybody but me to see it, and (2) the problem is that you do

```
from sys import stderr
```
WHOLE NEW CELL
```
stderr.write("HELLO")
stderr.flush()
```

This won't work because sys.stdout and sys.stderr are replaced at the beginning of each evaluation, so their output can be captured.   You could do this instead:
```
sys.stderr.write("HELLO")
sys.stderr.flush()
```
