### ISSUE TITLE
Published iPython notebook in HTML format is not scrollable

### ISSUE THREAD

**Issue by ryanmcfall** [sagemathinc/smc#359]
I have published an iPython notebook using the Publish button, which gives me the following URL:

https://cloud.sagemath.com/projects/e165af06-036c-4bf1-b3f1-178697a8dda9/files/Moodle%20RSS%20to%20Social%20Media/Parse%20Moodle%20Activity%20feed.html

When this HTML document is viewed in either Chrome or Internet Explorer on Windows 8, as well as Safari on a Mac, the document is not scrollable.

**Comment by haraldschilly** [comment]
hi, this is maybe an oversight by me due to a recent change ... or some old subtle bug. in any case, it shouldn't be hard to fix.

note, that the direct link (with "raw" in the URL) to the html file works as you expect it:

https://cloud.sagemath.com/e165af06-036c-4bf1-b3f1-178697a8dda9/raw/Moodle%20RSS%20to%20Social%20Media/Parse%20Moodle%20Activity%20feed.html

**Comment by haraldschilly** [comment]
rollout complete
