### ISSUE TITLE
making it so `%matplotlib inline` isn't needed

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#37]
See this thread for many great solutions!

  http://mail.scipy.org/pipermail/ipython-dev/2015-July/016631.html

**Comment by williamstein** [comment]
@jasongrout -- any thoughts about this?

**Comment by jasongrout** [comment]
this was also asked recently on the mailing list.  I'll dig up the answer...

**Comment by jasongrout** [comment]
See https://groups.google.com/forum/#!topic/jupyter/kjpZGqCVvA0

"You can put a standard ipython_kernel_config.py file in /etc/ipython/ where it will affect all users. The config to make matplotlib plots inline should be:

c.InteractiveShellApp.matplotlib = 'inline'

This will cause matplotlib to be loaded whenever a kernel is started. We're working on more sophisticated ways that don't force it to load matplotlib."

**Comment by williamstein** [comment]
Very nice -- thanks!!

**Comment by haraldschilly** [comment]
Hmm, I've just found this referenced in one of williams tasks. I've added a configuration to make plots inline right into all the jupyter kernels we are using. So, I think that's not the global configuration you are talking about, but it's working now. 

i.e. 

    import matplotlib.pyplot as plt
    plt.plot([1,2,3])

in a new jupyter/sage worksheet and boom you go.

slightly related and hijacking this thread because you are getting emailed about it: **is there a way to automatically load an extension via a kernel configuration?** I.e. in a Python2/SageMath Jupyter WS, one has to do `%load_ext sage` to get all the SageMath symbols. Would be cool if they are already loaded when firing up!

**Comment by jasongrout** [comment]
Sorry, just saw this. When you launch a kernel, you can run whatever code you want, for example:

```python
ip=get_ipython()
ip.run_line_magic('timeit', '1+2')
```
So I think it might work to just change your kernel to run those lines at the very start...

**Comment by williamstein** [comment]
long since done, right?

**Comment by jasongrout** [comment]
Fyi, at scipy @tacswell talked about how they were going to make mpl smarter about choosing a backend so you maybe wouldn't ever need to do this, even in a configuration.

**Comment by haraldschilly** [comment]
> long since done, right?

yes, all the kernels contain the explicit mpl inline definition.

not sure about how to make it smarter, but it wouldn't harm :-)
