### ISSUE TITLE
limit disk quota removal by the last known total disk usage + some overhead

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#453]
when removing disk quotas from a project, limit the amount of upgrades that can be freed by the last reported disk usage of the project (plus some overhead, like 5% or 100mb)

**Comment by williamstein** [comment]
In the k8s rewrite projects can always start up, since quota just gets raised to the minimum to allow startup.  We'll then (not done) add a VERY ANNOYING banner in red over the file listing saying -- you're over quota, deal with it.  I think this is a better approach than what you suggest here.   I do realize people could more easily abuse our system... but they can anways due to snapshots.
