### ISSUE TITLE
latex preview broken images → increase dpi

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#485]
sometimes, the gs utility produces preview png files from the pdf, that cannot be displayed. increasing the dpi resolution from 150 to 200 did fix this. is this a bug of gs, or a bad setting? 200dpi should be fine, though …

**Comment by williamstein** [comment]
Give me an example!

**Comment by williamstein** [comment]
Low since I've never seen this; hard since no way to reproduce (?).

**Comment by williamstein** [comment]
The default dpi has been 200 for a while.

However, a related issue is that resolution setting is in fact bizarrely hard-coded to 200 and setting it is ignored!  I'll fix that instead with a default of 200.

The relevant doc that you wrote this issue because of was some luatex thing from last year... (ticket 2007 in zendesk).

**Comment by williamstein** [comment]
Changing the default back to 150, since even on that old dock, using 150 seems to work.  Also 200^2 is almost twice 150^2, hence almost twice the time and bandwidth per preview, for almost no visible change.  So I'm changing the default to 150.

I also made it so the conf button works and saves change to local storage.
