### ISSUE TITLE
Current Directory Behavior when Switching Files

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#489]
As requested by various people, when clicking on the files tab after opening files and switching between them, return the directory where the user last was instead of the directory where the last open file was.

## Behavior Definition
- If a user opens file first/path/file1.ext and then opens other/path/file2.ext from the file listing and then using the tabs switches back to file1.ext, going back to the file listing should put the user at other/path/ and not first/path/.
- If a user opens a file via a link, say, foo/bar/filename.ext, navigating to the file listing should put the user at foo/bar/ and not the home directory.
- If a user opens two files, both via links, first/path/file1 and other/path/file2, the path of the last file they had open should be where the file listing puts them. (Is this even possible?)

Edit: Make it an option under settings.

**Comment by williamstein** [comment]
This needs to be an option.  It can be enabled by default but must be configurable.   I personally wouldn't use this at all and instead want the current behavior (or at least what it should be if it weren't broken), which is show the directory of the file currently being viewed, which is exactly the behavior of Gnu Emacs (one of the best editors of all time...).

**Comment by johnjeng** [comment]
Where is current behavior broken from expectation?

**Comment by williamstein** [comment]
It often just doesn't work somewhat randomly based on timing and randomness
of state.  Once the next level up is rewritten using React.js -- which has
not been done yet -- then this flakiness will be clearly eliminated (since
the directory to show will be in a store).

Any code you write at the moment related to this issue will be likely gone
when the react rewrite happens so try not to put too much time into it.


On Sun, Mar 27, 2016 at 5:01 PM, John Jeng <notifications@github.com> wrote:

> Where is current behavior broken from expectation?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemathinc/smc/issues/489#issuecomment-202170614>
>



-- 
William (http://wstein.org)

**Comment by johnjeng** [comment]
Simply switching to the new scheme seems to involve just commenting one line of code. However, I'm still not 100% clear on how to add new user fields to the database so I'll just let this one sit for little bit longer.

**Comment by johnjeng** [comment]
Found original issue at #423.
