### ISSUE TITLE
install tensorflow

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#510]
https://github.com/tensorflow/tensorflow 

Requested by: 思齊鍾

**Comment by haraldschilly** [comment]
tensorflow is installed in anaconda

**Comment by williamstein** [comment]
Having it in sage also evidently is broken due to a conflict between two sympy (or something similar) libraries.

**Comment by haraldschilly** [comment]
The libs are snappy vs. SnapPy … and in particular, i think we would make more unhappy if we throw SnapPy over board than we would make happy by installing TF in sagemath. Maybe SnapPy should rename itself to use CameCases, but that's not our call. I've emailed the developers. Is there a label for upstream?

**Comment by dimpase** [comment]
I wonder whether Absolute/Relative path stuff might be a better way forward, to avoid SMC vs Sage discrepancies as much as possible.
In principle relative imports allow for having equally named modules in different directories.
Note that pip allows for an alternative installation directory, so that installation into different directories is not a big deal. We can do this for snappy in Sage then.

     pip install --install-option="--prefix=$PREFIX_PATH" package_name

Then we would just do, in Sage: 

     from __future__ import absolute_import
     from .snappy import <stuff>
     <more stuff>

and this would not clash with python-snappy. 

For the reference, snappy's Sage ticket is [#20739](https://trac.sagemath.org/ticket/20739) and currently needs work.

**Comment by NathanDunfield** [comment]
Does tensorflow really require "python-snappy" or even the associated C++ compression library?  I tried out the official tensorflow [Docker image](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#docker-installation), and there "import snappy" gives an ImportError.  Moreover, I couldn't find the "libsnappy" compression library, and definitely the corresponding Ubuntu package was not installed (trusty/libsnappy1).  

Of course, it might be that tensorflow works better with "python-snappy", I have never used either.  However, depending on the relative popularity of snappy (topology) and snappy (compression library) on SMC, you could consider installing tensorflow (sans python-snappy) and snappy (topology) centrally, and then having those using python-snappy just do "pip install python-snappy --user".  Actually, I'm not 100% sure about that last idea, as while USERSITE does have precedence in the search order, I'm not if higher version number still wins out, which would be a problem since snappy (topology) is on 2.4 and python-snappy (compression) is on 0.5.  

In general, virtual environments is another tool to deal with needing to keep different versions of Python packages around...

**Comment by haraldschilly** [comment]
Back then, I was installing the wheel package, and when doing some tests I stumbled over this. Maybe something has changed in the meantime and this issue is actually gone, that would be great :-)
About where it is actually used, IIRC it was inside the protobuf library or some combination of using protobuf and snappy.

**Comment by NathanDunfield** [comment]
The Docker image for tensorflow does have protobuf installed.  I tried installing snappy (topology) on this Docker image and it worked without a hitch --- the doctests even all passed.

**Comment by haraldschilly** [comment]
Ok, I went through some details again, sorry for wasting everyone's time :walking: 

It works and I'm pushing a fix for our SMC build instructions. The whole issue seems to have been caused by protobuf in the first place, which I could just omit now with a newer tensorflow version.
