### ISSUE TITLE
Open command does not work in SMC inside SMC when using Tmux

### ISSUE THREAD

**Issue by timothyclemansinsea** [sagemathinc/smc#563]
In order to fix this one has to do `unset TMUX` in their terminal that is running in SMC inside SMC.

**Comment by johnjeng** [comment]
This works for me. Will reopen if it's actually broken still.

**Comment by williamstein** [comment]
I think it is still broken. I think illustrate this you have to run tmux first in the parent project, then do start_hub inside that tmux session.   The tmux environment is then inherited by all subprocesses, including terminals in projects. 

The fix is probably to simply add the line `unset TMUX` to `dev/project/start_hub`...
