### ISSUE TITLE
Making SMC Hybrid

### ISSUE THREAD

**Issue by soorho** [sagemathinc/smc#570]
## SMC integrated with Sage Math Notebook (SMN)
The easy initialization and the portability of files are the major advantages of cloud IDEs, while the ability to freely use and control the computer system is the major advantage of noncloud IDEs. By integrating with SMN, SMC will become a better cloud that has advantages of both clouds and nonclouds.

Integrating SMC with SMN may be done in a way such that:
   - such a feature can be given as a present to people who donate,
   - SMC at start automatically executes SMN,
   - SMN is without any user interface, since SMC prints outputs,
   - files are run by the local system via SMN,
   - files are stored in the server of SMC,
- the internet latency problem is solved because the local system runs files, and the internet acess is required only for storing files.

Can You please do this? :)

**Comment by williamstein** [comment]
- What is "Sage Math Notebook (SMN)"?  I've never heard of it.

- What does "By integrating with SMN" mean?

- "the internet latency problem is solved because the local system runs files, and the internet acess is required only for storing files.":  Are you just describing Dropbox?

This issue is very vague so I'm closing it; please re-open if you plan to clarify it a lot.
