### ISSUE TITLE
"Publish" (to HTML) option for Markdown files 

### ISSUE THREAD

**Issue by marks** [sagemathinc/smc#625]
Just like I can publish a Jupyter notebook to HTML, I'd love to do this for my Markdown docs

**Comment by williamstein** [comment]
We need a good markdown to html convertor.  See the discussion in the issue about printing markdown also:   https://github.com/sagemathinc/smc/issues/852

**Comment by williamstein** [comment]
@haraldschilly -- done right?  closing.

**Comment by haraldschilly** [comment]
no, there is only pandoc creating a pdf. I tried pandoc for an html output, but that wasn't satisfying.

**Comment by williamstein** [comment]
Wait a minute.  Now if you publish a .md file and somebody views it, they already see it rendered properly (as html).  So there is no need for this.  Also, "I can publish a Jupyter notebook to HTML," is actually not desirable -- it was just a hack that caused confusion and we got rid of.  Closing this again, since it is not necessary.
