### ISSUE TITLE
files don't seem to get "deleted"

### ISSUE THREAD

**Issue by simonluu** [sagemathinc/smc#668]
When you delete a file and another file that is created with the same name, it has the same contents as the file that you tried to delete. This is especially weird for chats.

**Comment by johnjeng** [comment]
Can confirm. 

Tried `rm [file name]`, checked that I couldn't find it anywhere, then did `touch [file name]` and the same file appeared.

@williamstein Certainly this can't be intentional..?

**Comment by williamstein** [comment]
It's totally 100% "intentional"... but only in the sense that proper file move and rename has *NOT* been implemented yet.        There are some tricky basic questions involved here, which just haven't been sorted out.    It would be great if you thought about them.  At least describe precisely what expected behavior should be.

**Comment by johnjeng** [comment]
I'm wondering which tricky basic questions you're referring to. I would love to think about them but I'm not sure what it is I should be thinking about.

**Comment by williamstein** [comment]
For starters, just clearly state expected behavior.  E.g., if you use the UI to move a file, what happens to its history?  What happens to the other people/browsers that have that file open?  Same question about delete?

**Comment by johnjeng** [comment]
Ahhhh. Gotcha. Okay.

**Comment by timothyclemansinsea** [comment]
I implemented real delete

**Comment by johnjeng** [comment]
Whoa whoa whoa. What?
1. Where?
2. What happens for someone who has a file open?
3. What about old links?

**Comment by williamstein** [comment]
1. @timothyclemansinsea  made it (as https://github.com/sagemathinc/smc/pull/484) so when you use the UI to delete  a file, then instead of it moving to the trash it is immediately deleted.  This makes sense in light of snapshots.  However, like with Dropbox, it would be good to mention this as part of the delete dialog, with a link to snapshots.  

2. Incidentally, today I made some bug fixes related to sync; one of them is that when a file is open and deleted, a field "deleted" in the syncstrings table is set to true, and clients can then *close* the file if they have it open.   I implemented actually doing the close in this case for codemirror file editors, but nothing else.   You can try this out live, assuming you refresh you browser and your project was restarted in the last hour or two.    If you then explicitly open the file again in the UI, it is created (with the same history).  Also, if you touch or copy a file back with the same name, it is also then possible to edit it.  Clicking on an old link will create the file as empty, but with its history.

**Comment by williamstein** [comment]
I think I fixed this.
