### ISSUE TITLE
sagews syntax error after indentions

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#70]
this gives a syntax error:
```
for i in range(1):
    pass
'x'
```
or this
```
if True:
    pass
"x"
```
like
```
Error in lines 1-3
Traceback (most recent call last):
  File "/projects/20e4a191-73ea-4921-80e9-0a5d792fc511/.sagemathcloud/sage_server.py", line 879, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "<string>", line 3
    'x'
      ^
SyntaxError: invalid syntax
```

while this works:

```
y = 2
"x"
```

**Comment by DrXyzzy** [comment]
Problem is caused by the last line starting with a string literal. Workaround is to put the literal in parens.

Explanation: function [sage_parsing.divide_into_blocks](https://github.com/sagemathinc/smc/blob/master/src/smc_sagews/smc_sagews/sage_parsing.py#L219) merges a line that starts with a literal to the previous block. This causes `exec compile(block+'\n', '', 'single')` to fail in [sage_server.Salvus.execute()](https://github.com/sagemathinc/smc/blob/master/src/smc_sagews/smc_sagews/sage_server.py#L947) because block is not a single statement.

Problem goes away if check `code[i][:2] == '%('` is eliminated in the while statement near [sage_parsing.py:219](https://github.com/sagemathinc/smc/blob/master/src/smc_sagews/smc_sagews/sage_parsing.py#L219). Is there some other case that will fail if this test is removed?

**Comment by williamstein** [comment]
Now live.
