### ISSUE TITLE
have sagews %python3 mode use jupyter python3 kernel

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/smc#739]

**Comment by DrXyzzy** [comment]
Plan:

1. Replace existing %python3 with jupyter bridge running anaconda3 kernel. Work on this enhancement will also take care of #740.
1. Fix so error output with ANSI codes is displayed in color:

    ```
    %a3
    xyz*
    # output below here --
    [0;36m  File [0;32m"<ipython-input-1-1e273f11e5d1>"[0;36m, line [0;32m1[0m
    [0;31m    xyz*[0m
    [0m        ^[0m
    [0;31mSyntaxError[0m[0;31m:[0m invalid syntax
    ```
1. Add support for python3 `input()`which causes cell execution to hang at present.

**Comment by haraldschilly** [comment]
I just saw this ticket when clicking through this pile here. I'm in general more happy, if `%python3` uses the system-wide `/usr/bin/python3` and `%anaconda3` uses `$ANACONDA3/bin/python` (the "3" just means that it is python 3 based).

I'm saying this, because I did some work towards those new compute images for the k8s switch, which actually have 4 different python environments. This would also imply, that a `%python2` is using `/usr/bin/python2`.

**Comment by DrXyzzy** [comment]
Just saw comment from @haraldschilly above, but this is not about /usr/bin environments, but rather about which jupyter kernel to use with `%python3` mode. Recommendation in 2016-07-23 chat was to run the `anaconda3` kernel with the built-in `%python3` mode.

**Comment by DrXyzzy** [comment]
Done.
