### ISSUE TITLE
chat preview toggle needs to be in account setting

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#794]
I disabled the new chat realtime preview toggle since even changing tabs would forget how it was set, which isn't good.  Toggling it needs to set something in account settings, which persists and is sync'd, like font sizes, etc.  And there could also be the same setting over in account settings....

**Comment by williamstein** [comment]
I'm also not sure we need to make this toggleable -- who doesn't want preview?  If so, why?

**Comment by haraldschilly** [comment]
Wasn't the plan to synchronize the preview with others? There were objections that such partially written messages shouldn't be visible to others.

**Comment by williamstein** [comment]
I'm initially for making preview sync'd and live.  @johnjeng is against it.  He might be right -- I don't know.

**Comment by simonluu** [comment]
I think that there should be an option in the account settings that sets whether or not chat preview starts out enabled or disabled and then a button in the chat that you can turn on and off. So while you are typing a message you can turn it off while you are typing and then turn it back on before you send the message. I can add a X in the top right of the preview box to close the preview.

> changing tabs would forget how it was set

I can fix it so that it remembers how it was set.
