### ISSUE TITLE
support Colormap for implicit_plot3d and parametric_plot3d

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#829]
This is colorful:
```
var("x y z")
T(x,y,z) = sin(2*y + 3*z)^2
cm = colormaps.gist_rainbow
g = implicit_plot3d(x^2 + y^2 + z^2, (x,-2, 2), (y,-2, 2), (z,-2, 2), contour=2, color=(T, cm), plot_points=4)
show(g, viewer='tachyon')
```
but this isn't
``
show(g)
```

It seems like the `g.obj()` function simply doesn't have any information about the colors of faces, and the SMC graphics rendering depends on that.  

See https://github.com/sagemathinc/smc/pull/352  is supposed to fix this but doesn't work at all.  Changing the off by one error makes it not broken.

Any ideas?   Maybe the obj method on 3d plots needs to be further implemented?  Or something else.

**Comment by fchapoton** [comment]
Bad news: one cannot currently use the obj method to get the colors. The obj format has the peculiarity of separating in two files the geometric data and the texture/color data. The texture/color file is not implemented for colored triangulations.

Good news: I have prepared the ground in trac ticket https://trac.sagemath.org/ticket/19817 (which is closed since a long time) by adding two functions: one allowing to known if the object has faces of various colours or not, the other one giving all the necessary information to build the json data, including colors.

There remains to make good use of these new functions.
