### ISSUE TITLE
Print Button Problems

### ISSUE THREAD

**Issue by johnjeng** [sagemathinc/smc#852]
List of problems
- [x] Does nothing in Codemirror editor. ie. `file_name`, `thing.txt`, 
- [x] Entirely useless in html editor
- [x] Conversion from markdown to pdf is not great
  - lists don't work

**Comment by williamstein** [comment]
Lists do work, but the markdown "standard" is different, e.g., it requires the nested lists to be done using asterisks.   It uses pandoc I think; I don't know if there is a better alternative in existence today -- search around!     In 2013 pandoc was probably the best choice.  Today?  I doubt it.

**Comment by johnjeng** [comment]
This website seems to convert markdown pretty well. https://gitprint.com/

Looking in the [git repo](https://github.com/adamburmister/gitprint.com/blob/master/routes/index.js), it looks like he uses [markdown-pdf](https://github.com/alanshaw/markdown-pdf)

**Comment by williamstein** [comment]
See also this feature request: https://github.com/sagemathinc/smc/issues/82

**Comment by williamstein** [comment]
See https://github.com/sagemathinc/smc/pull/1160

**Comment by haraldschilly** [comment]
I'll fix it, it's something many use and it should work or not work in a
well defined way.

**Comment by williamstein** [comment]
Plan:
1. Make a list of editors that have a print button and the status of the implementation.
2. Make it non-buggy, either by explicitly eliminating the print button, or using a better approach to printing.
3. For those editors that should have printing, but don't, create enhancement tickets to implement printing, and do that after all bugs are fixed.

**Comment by haraldschilly** [comment]
my status on this is, that I've collected "print" utility classes in a new "printing" module. That's necessary, because there are cross-cutting concerns between the editors (e.g. txt can be printed via pandoc like md or html, but it is not suitable for the specialized md-html editor).

based on that information, the UI only shows and arms the print button, if there is a known class for printing the file.

the status I've collected so far is the following:

* sagews → SagewsPrinter (calls this print_to_pdf on the backend, which is actually only for sagews ... could be refactored)
* tex → LatexPrinter (checks if the pdf exists, then opens it in a new tab)
* ['md', 'html', 'htm', 'rst', 'wiki', 'mediawiki', 'txt'] → PandocPrinter (calls pandoc, then opens pdf)

fixing the actual printing of specific document types (or even adding new printers) should be further more specific tickets.

**Comment by haraldschilly** [comment]
@johnjeng I've checked your boxes above, since my branch for printing deals with all of it. regarding markdown in particular, it handles nestes lists like

```
- xycv
- yxcv
    * yxcv
    * 23roij2
        - 123123
        - 123123
```

just as well, as it handles our default markdown table and formulas.

**Comment by williamstein** [comment]
fixed by pr 1160.
