### ISSUE TITLE
jupyter bridge: wrong newlines with print vs. display of last object

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#862]
When running this in  a sagews, I get a funny output. Probably just a wrongly timed or missing `\n`:

```
%sage
a3 = jupyter("anaconda3")
---
%a3
x=1
print("x = %s" % x)
x
```

![smc-jupyter-bridge-output-bug](https://cloud.githubusercontent.com/assets/207405/18202191/cc9a24f8-710e-11e6-9cb2-fc80011e8b7a.png)

**Comment by DrXyzzy** [comment]
Problem is that, in order to get ANSI color to show, most text output from jupyter is wrapped in html `<pre>...</pre>`, and that automatically inserts either newline or space. Either choice will cause a problem sometime.

Proposed workaround for this bug is to bypass the html-ansi wrapper if output does not contain the ansi CSI (Control Sequence Introducer) "\1b[". There will still be cases that don't line up properly, but lots fewer of them.

**Comment by DrXyzzy** [comment]
Done. Verified in production manually and passes sagews pytest suite:
```
collected 58 items
...
58 passed in 80.79 seconds
```
