### ISSUE TITLE
TeX editor indicates a syntax error on $$\text{if $x>0$}$$

### ISSUE THREAD

**Issue by semorrison** [sagemathinc/smc#87]
The TeX editor highlights in the innermost `$` signs in `$\text{if $x>0$}$` in red, incorrectly indicating a syntax error.

Other variations, such as `$\text{if $x>0$}$` or `\begin{equation*}\text{if $x>0$}\end{equation*}` work fine.

**Comment by williamstein** [comment]
Example: https://cloud.sagemath.com/projects/4a5f0542-5873-4eed-a85c-a18c706e8bcd/files/support/2016-09-23-141356-issue87.sagews

**Comment by williamstein** [comment]
I think we should close this. Codemirror only uses regexps for syntax highlighting.   I think it's provably impossible to properly syntax highlight this sort of thing in general without actually parsing latex, since one could alias \text to any other macros name, e.g., \foo, and suddenly $$\foo{if $x>0$}$$ should highlight differently due to this alias. 

So sorry.

**Comment by haraldschilly** [comment]
sounds good, when I read the ticket a few days ago I also thought that this
isn't decidable.
