### ISSUE TITLE
chat room markdown/html rendering does some weird stuff

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/smc#874]
E.g., if you type

    `<User />`

then it comes out `<user></user>` which is pretty disturbing.

**Comment by haraldschilly** [comment]
I bet that's the html sanitization. An overall proper solution would be to have a custom html parser that's markdown aware, and encode the input message right from the start, and then getting rid of all that post processing of the string. I fear, getting this right in general is rather hard to do, though, since my last attempt in doing this failed by the lack of support for some tags with those standard sanitizers. Maybe the tool behind these github comments here is known?

**Comment by williamstein** [comment]
See also https://github.com/sagemathinc/smc/issues/574, which I closed in favor of this.

**Comment by williamstein** [comment]
From https://github.com/sagemathinc/smc/issues/227: 

Tim Abbott:

> ... you may want to check out our Markdown configurations/implementations, which we have in both JS and Python:  https://github.com/zulip/zulip/blob/master/zerver/lib/bugdown/__init__.py#L858  (uses the python-markdown library).  https://github.com/zulip/zulip/blob/master/static/js/echo.js#L395 (uses the marked library)

As SMC uses the same underlying markdown libraries, this should be easy.  Basically the point of this ticket is to compare notes/options, which we've both arrived at with use testing.
