### ISSUE TITLE
SMC IPython Notebook tabs do not keep scroll state

### ISSUE THREAD

**Issue by LukasDrude** [sagemathinc/smc#9]
This issue occurs in Firefox and in the chromium app:

Reproduce 1:
 a) Scroll in one IPython notebook.
 b) Select a second notebook.
 c) Return to scrolled notebook: The view is returned to the top of the notebook.

Reproduce 2:
 a) Click on a folder in the file browser.
 b) Select a notebook.
 c) Return to the file browser: The file browser will have returned to your home folder.

**Comment by williamstein** [comment]
1: I think this is an issue with how iframes work.  That said, it wouldn't be hard to save the scroll state and restore it.

2. The file browser behavior -- by design -- currently works like in Emacs.  The current working directory is whatever the directory is of the last tab you were viewing.    I will surely change this to be an option in account settings.   Changing anything in account settings was very painful... until recently; it's probably much easier now since I rewrote that page using React.js last week.

**Comment by williamstein** [comment]
This would be natural to address when doing the react rewrite of the "Jupyter notebook editor", i.e., the redux store containing the state and an iframe with normal jupyter in it.

**Comment by williamstein** [comment]
Long since fixed...
