### ISSUE TITLE
toggling sagews cells in %md collapses too much

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/smc#966]
When I have a document like this: %md, some code %md, code ... and the first cell is like that:

```
%md
## abc

test
```

then collapsing the h2 header collapses way too much: in the worksheet where I saw this, it was until the next h1 header in the next %md. it works well for codecells (i.e. the first for loop, def function, etc.)

**Comment by williamstein** [comment]
Fixing this might require forking and rewriting the code folding plugin.  That's probably not too hard due to it being only about 2 pages of code...  and yet still I bet it'll be pretty hard.  Basically we need to hack in some sort of way to terminate on cell markers.  I think I've already done exactly this sort of thing to the python mode to make the sagews mode itself.

**Comment by haraldschilly** [comment]
yes, I was expecting this is codemirror specific. I can imagine that this might also be seen as an intended feature, such that I can click-away a whole subsection including all the cells that are in it. It's just that I wouldn't expect this to happen at all :-)
